# Project identification
sonar.projectKey=Electro-Kerubin_Mantenedor-de-empresas-2.0
sonar.organization=electro-kerubin
sonar.projectName=Mantenedor de empresas 2.0

# Source code
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/tests/**,**/playwright-report/**,**/test-results/**
sonar.language=ts

# Tests and coverage
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8