name: Analisis de codigo con sonarqube
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (skip scripts)
        run: npm ci --ignore-scripts

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
